#!/usr/bin/env python3
"""Behavior tests for the ESP32-S3 public-release hygiene policy."""

from __future__ import annotations

import unittest

from check_public_release_hygiene import scan_text


class PublicReleaseHygieneTests(unittest.TestCase):
    def rules(self, text: str) -> set[str]:
        return {str(issue["rule"]) for issue in scan_text("docs/example.md", text)}

    def test_serial_placeholder_is_allowed(self) -> None:
        self.assertEqual(self.rules('port = "<SERIAL_PORT>"'), set())

    def test_assistant_marker_is_rejected(self) -> None:
        self.assertIn("ai_tool_residue", self.rules("generated by ChatGPT"))

    def test_local_assistant_path_is_rejected(self) -> None:
        self.assertIn("ai_tool_residue", self.rules(r".codex\skills\board\SKILL.md"))

    def test_personal_windows_path_is_rejected(self) -> None:
        self.assertIn("personal_absolute_path", self.rules(r"C:\Users\developer\project"))

    def test_personal_unix_path_is_rejected(self) -> None:
        self.assertIn("personal_absolute_path", self.rules("/home/developer/project"))

    def test_fixed_com_port_is_rejected(self) -> None:
        self.assertIn("fixed_windows_serial_port", self.rules("--port COM42"))

    def test_weak_password_is_rejected(self) -> None:
        self.assertIn("weak_default", self.rules('password="changeme"'))

    def test_project_attribution_is_allowed(self) -> None:
        self.assertEqual(self.rules("Copyright MROS Engineering - MCC45TR"), set())


if __name__ == "__main__":
    unittest.main()
